/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;

CREATE TABLE `netflow_in_hour` (
  `id` int(4) unsigned NOT NULL AUTO_INCREMENT,
  `tag` int(4) unsigned NOT NULL,
  `as_src` int(4) unsigned NOT NULL,
  `as_dst` int(4) unsigned NOT NULL,
  `peer_ip_src` char(45) NOT NULL,
  `peer_ip_dst` char(45) NOT NULL,
  `as_path` char(40) NOT NULL,
  `ip_src` char(45) NOT NULL,
  `ip_dst` char(45) NOT NULL,
  `port_src` int(2) unsigned NOT NULL,
  `port_dst` int(2) unsigned NOT NULL,
  `iface_in` int(4) unsigned NOT NULL,
  `iface_out` int(4) unsigned NOT NULL,
  `ip_proto` char(6) NOT NULL,
  `tcp_flags` int(4) unsigned NOT NULL,
  `packets` int(10) unsigned NOT NULL,
  `bytes` bigint(20) unsigned NOT NULL,
  `country_ip_src` char(2) NOT NULL,
  `country_ip_dst` char(2) NOT NULL,
  `stamp_inserted` datetime NOT NULL,
  `stamp_updated` datetime DEFAULT NULL,
  `tag2` int(4) unsigned NOT NULL,
  PRIMARY KEY (`id`,`stamp_inserted`),
  KEY `a` (`as_dst`),
  KEY `b` (`as_src`),
  KEY `c` (`ip_src`),
  KEY `d` (`ip_dst`),
  KEY `e` (`iface_in`),
  KEY `f` (`iface_out`),
  KEY `g` (`stamp_inserted`),
  KEY `h` (`tag`),
  KEY `i` (`tag2`),
  KEY `j` (`as_path`)
) ENGINE=InnoDB AUTO_INCREMENT=2599489964 DEFAULT CHARSET=utf8
/*!50100 PARTITION BY LIST (hour(stamp_inserted))
(PARTITION p0 VALUES IN (0) ENGINE = InnoDB,
 PARTITION p1 VALUES IN (1) ENGINE = InnoDB,
 PARTITION p2 VALUES IN (2) ENGINE = InnoDB,
 PARTITION p3 VALUES IN (3) ENGINE = InnoDB,
 PARTITION p4 VALUES IN (4) ENGINE = InnoDB,
 PARTITION p5 VALUES IN (5) ENGINE = InnoDB,
 PARTITION p6 VALUES IN (6) ENGINE = InnoDB,
 PARTITION p7 VALUES IN (7) ENGINE = InnoDB,
 PARTITION p8 VALUES IN (8) ENGINE = InnoDB,
 PARTITION p9 VALUES IN (9) ENGINE = InnoDB,
 PARTITION p10 VALUES IN (10) ENGINE = InnoDB,
 PARTITION p11 VALUES IN (11) ENGINE = InnoDB,
 PARTITION p12 VALUES IN (12) ENGINE = InnoDB,
 PARTITION p13 VALUES IN (13) ENGINE = InnoDB,
 PARTITION p14 VALUES IN (14) ENGINE = InnoDB,
 PARTITION p15 VALUES IN (15) ENGINE = InnoDB,
 PARTITION p16 VALUES IN (16) ENGINE = InnoDB,
 PARTITION p17 VALUES IN (17) ENGINE = InnoDB,
 PARTITION p18 VALUES IN (18) ENGINE = InnoDB,
 PARTITION p19 VALUES IN (19) ENGINE = InnoDB,
 PARTITION p20 VALUES IN (20) ENGINE = InnoDB,
 PARTITION p21 VALUES IN (21) ENGINE = InnoDB,
 PARTITION p22 VALUES IN (22) ENGINE = InnoDB,
 PARTITION p23 VALUES IN (23) ENGINE = InnoDB) */;
